### PR TITLE
Test project first pull request

### PR DESCRIPTION
**Pull request by andresporras3423**
use rspec to test the code on the ruby files

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @andresporras3423, @abcussi. Good work:clap:. However, let's consider the following:**

1. Undo changes made to .rubocop.yml



2. You have tested different scenarios within the flow of the entire match. Here is what you were expected to do. Test each public method in match **within a describe block**. You will have to use **let** to setup some variables as you may require for each test.



3. Ensure that each **it** block covers only a single **expectation** within your tests.


- Remember to test both negative and positive scenarios in each case




_**Kindly make these changes and submit another code review request.**_

**Cheers:stars:**

### Status: Changes Requested.

**Comment by andresporras3423** [comment]
Update for test_project

* undone changes made in stickler config file
* testing different situations for each method
* using not_to eq to test negative scenarios

**Review by mosesogwo — APPROVED** [review]
**Good one!:+1:. Your project is approved :heavy_check_mark:**

You can now merge the pull request.

**Good luck in your next project:stars:**

**Comment by andresporras3423** [comment]
Thank you Moses

**Pull request merged**
