### PR TITLE
Project setup first pull request to development branch

### PR DESCRIPTION
**Pull request by andresporras3423**
* Created executable file to the project
* Create folders bin and lib

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great Start @team :clap: However, small changes need to be made in order to get approval for the milestone. Check :arrow_down: 

* [x] The repo has a `lib` directory (with .gitkeep file OR any other **empty** file(s)). ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

- **[REQUIRED]** You only need one **main.rb** file, the second one is unnecessary. :pray: delete it

### That's it :relieved: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by andresporras3423** [comment]
I have made the changes required,

* Deleted the repeated main in bin folder
* create lib with a void file inside

**Review by Forison — APPROVED** [review]
## Status Approved 💚
# 🙋‍♂️ team
## Go ahead and merge to development and proceed to the next task
#### Happy coding💻
#### Addo Forison

**Comment by andresporras3423** [comment]
Thank you so much

**Pull request merged**
